os:
  - linux
  - osx

dist: trusty

language : c

compiler:
  - clang
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install --build-from-source libusb ; fi

script:
  - mkdir build
  - cd build
  - cmake .. && make

notifications:
  email:
    on_success: change
    on_failure: always
