os:
  - linux
  - osx
dist: trusty
language: c
compiler:
  - clang
  - gcc
addons:
  artifacts: true
  sonarqube: true
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install --build-from-source libusb ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then sudo apt-get install -y libaio-dev libavahi-client-dev libavahi-common-dev libserialport-dev libusb-1.0-0-dev libxml2-dev ; fi

env:
  global:
    - secure: We2ROEt69nCyx902cenuTUwfB6RVXEazRmLUkHNYBpLnhESsrQP4TGsRLc429ErtZbD4jUqogMvp9L5V9pGLqyxJLA3oLkgfLbEgfA1FimZ4QlnxxDh9WkPYMTwiCM8e6B+Bt/a8qA1ahRRU/yZWNJXtyWn7GYVJqsvpcNjKMao=
script:
  - mkdir build
  - cd build
  - cmake .. && make
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
notifications:
  email:
    on_success: change
    on_failure: always

before_deploy:
  - export RELEASE_PKG_FILE_DEB=$(ls *.deb)
  - export RELEASE_PKG_FILE_RPM=$(ls *.rpm)
  - export RELEASE_PKG_FILE_TB2=$(ls *.tar.bz2)
  - echo "deploying $RELEASE_PKG_FILE_DEB, $RELEASE_PKG_FILE_RPM, $RELEASE_PKG_FILE_TB2 to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: Bl7sfWp796+D7cF99+YdmbQjr5stXh4H/4hN2L5FNL0FEHL4XnIscSqySgy2NNmcqWF4Mz5WNXMZ9M8rYSNAiOndcaBYB+xvesAUbIdncwswgTNn2cj6yQbv0yR9qVUdoyczvZMK1vIc6GtKWWkh0AmgR04cAFffU3fr+78JHIw=
  file:
    - "${RELEASE_PKG_FILE_DEB}"
    - "${RELEASE_PKG_FILE_RPM}"
    - "${RELEASE_PKG_FILE_TB2}"
  skip_cleanup: true
  on:
    repo: analogdevicesinc/libiio
    tags: true
