trigger:
- main
- master
- staging/*
- 20*

pr:
- main
- master
- 20*

jobs:
- job: LinuxBuilds
  strategy:
    matrix:
      centos_7_x86_64:
        imageName: 'ubuntu-latest'
        OS_TYPE: 'centos_docker'
        OS_VERSION: 7
      centos_8_x86_64:
        imageName: 'ubuntu-latest'
        OS_TYPE: 'centos_docker'
        OS_VERSION: 8
      ubuntu_16_04_x86_64:
        imageName: 'ubuntu-16.04'
      ubuntu_18_04_x86_64:
        imageName: 'ubuntu-18.04'
      ubuntu_20_04_x86_64:
        imageName: 'ubuntu-20.04'
  pool:
    vmImage: $(imageName)
  steps:
  - checkout: self
    fetchDepth: 1
    clean: true
  - script: ./CI/travis/before_install_linux
    displayName: "Install Dependencies"
  - script: ./CI/travis/make_linux
    displayName: "Build"

- job: macOSBuilds
  strategy:
    matrix:
      macOS_10_14:
        imageName: 'macOS-10.14'
      macOS_10_15:
        imageName: 'macOS-10.15'
# FIXME: uncomment after this is resolved:
#        https://github.com/actions/virtual-environments/issues/2072
# Mac OS X 11.0 is definitely a big thing (with their switch to ARM,
# so we should be quick to have it)
#      macOS_11_0:
#        imageName: 'macOS-11.0'
  pool:
    vmImage: $(imageName)
  steps:
  - checkout: self
    fetchDepth: 1
    clean: true
  - script: ./CI/travis/before_install_darwin
    displayName: "Install Dependencies"
  - script: ./CI/travis/make_darwin
    displayName: "Build"
